name = "NetCDF"
uuid = "30363a11-5582-574a-97bb-aa9a979735b9"
keywords = ["NetCDF", "IO"]
license = "MIT"
desc = "NetCDF file reading and writing"
version = "0.11.4"

[deps]
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
NetCDF_jll = "7243133f-43d8-5620-bbf4-c2c921802cf3"

[compat]
DiskArrays = "0.2, 0.3"
Formatting = "0.3.2, 0.4"
NetCDF_jll = "400.701.400, 400.702.400, 400.702.402"
julia = "1.3"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
