name = "NetCDF"
uuid = "30363a11-5582-574a-97bb-aa9a979735b9"
keywords = ["NetCDF", "IO"]
license = "MIT"
desc = "NetCDF file reading and writing"
version = "0.9.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
CondaBinDeps = "a9693cdc-2bc8-5703-a9cd-1da358117377"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
DiskArrays = "3c3547ce-8d99-4f5e-a174-61eb10b00ae3"

[compat]
BinDeps = "0.8.10, 1.0"
CondaBinDeps = "0.1.0"
Formatting = "0.3.2, 0.4"
julia = "1.0.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
